spring:
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
    open-in-view: false
    datasource:
      # H2 file remote client: jdbc:h2:tcp://localhost:9092/~/choosing
      url: jdbc:h2:file:~/choosing
      data-username: sa
      data-password: WdyHMa4G
    data:
      rest:
        base-path: api
        return-body-on-update: true
    jackson:
      serialization:
        indent-output: true
